/**
 * Pinned publisher public keys + registry signature verification.
 * Ed25519, via Node's built-in `crypto` — no new dependency for signing.
 *
 * The app trusts a small pinned *list* of public keys, not one hardcoded
 * key, so a future rotation is additive.
 *
 * IMPORTANT: there is **no production key yet** — real key generation,
 * GitHub Actions secrets, and authenticated production distribution are all
 * still deferred (see the `mosaic-addons` README's GO-LIVE TODO). So
 * `PRODUCTION_PUBLISHER_KEYS` is deliberately empty and a packaged build
 * trusts nothing: every registry signature fails to verify, which is the
 * correct behaviour while no signed catalogue is published.
 *
 * **No key material is committed to this repository, in any form.** Two
 * dev/test public keys (`4b7d6575`, `78e2469a`) used to be pinned here, with
 * their private halves committed as test fixtures. Both fixtures were removed
 * on 2026-08-21 and the pins with them. A private key in a repo is a private
 * key on the internet the moment that repo is public, and git history keeps it
 * there afterwards — `4b7d6575`'s private half has been in this public repo's
 * history since #96 and must be treated as permanently compromised. It is
 * pinned nowhere, so that costs nothing, but it is why the rule is now
 * absolute rather than case-by-case.
 *
 * A dev build can still exercise the verify path: it trusts public keys
 * supplied *at runtime* via `MOSAIC_DEV_PUBLISHER_KEYS` (see
 * `devPublisherKeys`), never anything checked in. Test keys are generated by
 * the same offline ceremony as production and kept outside any working tree.
 *
 * Trusting a key in a release build means anyone holding its private half can
 * sign a registry the app accepts — and an accepted registry leads, via
 * `confirmInstall`, to running an addon's `main/index.js` in the main process.
 * Hence the `app.isPackaged` gate, which fails closed.
 */

import { app } from "electron";
import { createPublicKey, createHash, verify as cryptoVerify } from "crypto";
import { readFileSync } from "fs";

export interface TrustedPublisherKey {
  /** First 8 hex chars of sha256(SPKI DER public key bytes) — computed once at generation. */
  keyId: string;
  /** Ed25519 public key, SPKI/PEM. */
  publicKey: string;
  /** ISO date or app-version string — documentation only, not range-checked. */
  introducedAt: string;
  /** Set once a later release stops shipping this key — documentation only. */
  retiredAt: string | null;
}

/**
 * Real publisher keys. Empty until the production `mosaic-addons` key is
 * generated under the offline custody procedure and pinned here as its own dated
 * entry. Adding the first entry is what turns the signed catalogue on.
 */
export const PRODUCTION_PUBLISHER_KEYS: TrustedPublisherKey[] = [];

/**
 * Dev/test trust anchors, supplied at runtime and **never committed**.
 *
 * Set `MOSAIC_DEV_PUBLISHER_KEYS` to the path of a JSON file holding an array
 * of `TrustedPublisherKey` (public halves only). Consulted solely in an
 * unpackaged build — a packaged build ignores it entirely, so a stray
 * environment variable on a user's machine can never widen what a shipped app
 * trusts.
 *
 * Generate the corresponding keypair with the same offline ceremony used for
 * production, and keep the private half outside every working tree.
 */
export const DEV_PUBLISHER_KEYS_ENV = "MOSAIC_DEV_PUBLISHER_KEYS";

function devPublisherKeys(): TrustedPublisherKey[] {
  const source = process.env[DEV_PUBLISHER_KEYS_ENV];
  if (!source) return [];
  try {
    const parsed = JSON.parse(readFileSync(source, "utf8"));
    if (!Array.isArray(parsed)) {
      console.warn(`[addons/signing] ${DEV_PUBLISHER_KEYS_ENV} must hold a JSON array of public keys`);
      return [];
    }
    const keys = parsed.filter(
      (k): k is TrustedPublisherKey =>
        Boolean(k) && typeof k.keyId === "string" && typeof k.publicKey === "string",
    );
    // Refuse anything carrying a private half — that file should never exist,
    // and silently accepting one would normalise the thing this guards against.
    for (const entry of parsed) {
      if (entry && typeof entry.privateKeyPem === "string") {
        console.error(
          `[addons/signing] ${DEV_PUBLISHER_KEYS_ENV} contains private key material — refusing all of it. ` +
            `Supply public halves only.`,
        );
        return [];
      }
    }
    if (keys.length > 0) {
      console.warn(
        `[addons/signing] Dev build: trusting ${keys.length} publisher key(s) from ${DEV_PUBLISHER_KEYS_ENV} ` +
          `(${keys.map((k) => k.keyId).join(", ")}). Never set this in a packaged build.`,
      );
    }
    return keys;
  } catch (error) {
    console.warn(
      `[addons/signing] Could not read ${DEV_PUBLISHER_KEYS_ENV}: ${error instanceof Error ? error.message : String(error)}`,
    );
    return [];
  }
}

/**
 * The keys this build actually trusts. Fails closed: if `app` is somehow
 * unavailable (imported outside Electron) `isPackaged` reads as `undefined`
 * and we treat the build as packaged, so only production keys apply — and
 * there are none yet.
 */
export function trustedPublisherKeys(): TrustedPublisherKey[] {
  const packaged = app?.isPackaged ?? true;
  return packaged ? PRODUCTION_PUBLISHER_KEYS : [...PRODUCTION_PUBLISHER_KEYS, ...devPublisherKeys()];
}

export interface RegistrySignatureEnvelope {
  keyId: string;
  signature: string; // base64
}

export interface VerifyRegistryResult {
  verified: boolean;
  keyId?: string;
  reason?: string;
}

/**
 * Verify `bytes` (the raw `addon-registry.json` file contents) against
 * `envelope`. Looks up `envelope.keyId` in the pinned list — **not found →
 * reject immediately**, no fallback to trying every pinned key, no silent
 * accept. Only a passing signature check trusts the registry.
 */
export function verifyRegistry(bytes: Buffer | string, envelope: RegistrySignatureEnvelope): VerifyRegistryResult {
  if (!envelope || typeof envelope.keyId !== "string" || typeof envelope.signature !== "string") {
    return { verified: false, reason: "Malformed signature envelope" };
  }

  const pinned = trustedPublisherKeys().find((k) => k.keyId === envelope.keyId);
  if (!pinned) {
    return { verified: false, reason: `Unrecognized signing key "${envelope.keyId}"` };
  }

  let signatureBuf: Buffer;
  try {
    signatureBuf = Buffer.from(envelope.signature, "base64");
  } catch {
    return { verified: false, keyId: pinned.keyId, reason: "Malformed signature encoding" };
  }

  try {
    const keyObject = createPublicKey(pinned.publicKey);
    const data = typeof bytes === "string" ? Buffer.from(bytes, "utf8") : bytes;
    // Ed25519 verification via Node's crypto.verify — algorithm must be
    // `null` for Ed25519/Ed448 (the curve fixes the hash internally).
    const ok = cryptoVerify(null, data, keyObject, signatureBuf);
    if (!ok) return { verified: false, keyId: pinned.keyId, reason: "Signature does not match" };
    return { verified: true, keyId: pinned.keyId };
  } catch (error) {
    return { verified: false, keyId: pinned.keyId, reason: error instanceof Error ? error.message : String(error) };
  }
}

/** Exposed for test fixtures only — computes a keyId the same way key
 * generation does, so a test can double-check a generated key's id. */
export function computeKeyId(publicKeyPem: string): string {
  const keyObject = createPublicKey(publicKeyPem);
  const der = keyObject.export({ type: "spki", format: "der" });
  return createHash("sha256").update(der).digest("hex").slice(0, 8);
}
